document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta http-equiv=\'Content-Language\' content=\'zh-cn\'>");
document.writeln("<meta http-equiv=\'Content-Type\' content=\'text/html; charset=gb2312\'>");
document.writeln("<title>六肖八码</title>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("<table width=\'100%\' id=\'table23\' bordercolorlight=\'#ffffff\' bordercolordark=\'#ffffff\' style=\'font: 21px/28px tahoma, 微软雅黑, 宋体, arial, georgia, verdana, helvetica, sans-serif; color: rgb(68, 68, 68); text-transform: none; text-indent: 0px; letter-spacing: normal; word-spacing: 0px; white-space: normal; border-collapse: collapse; border-spacing: 0px; widows: 1; -webkit-text-stroke-width: 0px;\' bgcolor=\'#ffffff\' border=\'0\' cellspacing=\'0\' cellpadding=\'0\'>");
document.writeln("		<!-----------------开始复制-------------------------------->");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#ff9900\'>");
document.writeln("		<p align=\'center\'><font face=\'微软雅黑\'><b>第 119期:A级大公开;借钱拿高利贷也要大胆下注!</b></font></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font color=\'#00ff00\' face=\'微软雅黑\'>&nbsp;119期:推荐六肖:</font><font face=\"微软雅黑\" color=\"#FF0000\">加码王微信，免费领取⒈肖中特！</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font color=\'#00ff00\' face=\'微软雅黑\'>&nbsp;119期:推荐四肖:</font><font face=\"微软雅黑\" color=\"#FF0000\">微信：<span style=\"background-color: #FFFF00\">911188.COM</span></font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\' height=\"34\"><b><font color=\'#00ff00\' face=\'微软雅黑\'>");
document.writeln("		&nbsp;119期:推荐三肖:</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font color=\'#00ff00\' face=\'微软雅黑\'>&nbsp;119期:推荐二肖:</font><font face=\"微软雅黑\" color=\"#FF0000\">加码王微信，免费领取⒈肖中特！</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font color=\'#00ff00\' face=\'微软雅黑\'>&nbsp;119期:推荐一肖:</font><font face=\"微软雅黑\" color=\"#FF0000\">微信：<span style=\"background-color: #FFFF00\">911188.COM</span></font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font color=\'#00ff00\' face=\'微软雅黑\'>&nbsp;119期:主攻八码:</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>&nbsp;119期:主攻三码:</font><font face=\"微软雅黑\" color=\"#FF0000\">加码王微信，免费领取⒈肖中特！</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>&nbsp;119期:经典单双:</font><font face=\"微软雅黑\" color=\"#FF0000\">微信：<span style=\"background-color: #FFFF00\">911188.COM</span></font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>&nbsp;119期:平特一肖:</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>&nbsp;119期:平特一尾:</font><font face=\"微软雅黑\" color=\"#FF0000\">码王微信，免费领取⒈肖中特！</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>&nbsp;119期:中特五尾:</font><font face=\"微软雅黑\" color=\"#FF0000\">微信：<span style=\"background-color: #FFFF00\">911188.COM</span></font></b></td>");
document.writeln("");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#ff9900\'>");
document.writeln("		<p align=\'center\'><font face=\'微软雅黑\'><b>第 118期:A级大公开;借钱拿高利贷也要大胆下注!</b></font></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font color=\'#00ff00\' face=\'微软雅黑\'>&nbsp;118期:推荐六肖:</font><font face=\"微软雅黑\" color=\"#FF0000\">羊兔牛鼠龙</font><font face=\"微软雅黑\" color=\"#FFFFFF\">狗</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>&nbsp;118期:平特一尾:</font><font face=\"微软雅黑\" color=\"#FFFFFF\">22222尾</font></b></td>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#ff9900\'>");
document.writeln("		<p align=\'center\'><font face=\'微软雅黑\'><b>第 117期:A级大公开;借钱拿高利贷也要大胆下注!</b></font></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font color=\'#00ff00\' face=\'微软雅黑\'>&nbsp;117期:推荐六肖:</font><font face=\"微软雅黑\" color=\"#FF0000\">牛羊鼠马</font><font face=\"微软雅黑\" color=\"#FFFFFF\">狗</font><font face=\"微软雅黑\" color=\"#FF0000\">兔</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>&nbsp;117期:平特一肖:</font><font face=\'微软雅黑\' color=\'#FFFFFF\'>牛牛牛牛</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#ff9900\'>");
document.writeln("		<p align=\'center\'><font face=\'微软雅黑\'><b>第 116期:A级大公开;借钱拿高利贷也要大胆下注!</b></font></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font color=\'#00ff00\' face=\'微软雅黑\'>&nbsp;116期:推荐六肖:</font><font face=\"微软雅黑\" color=\"#FF0000\">龙牛狗</font><font face=\"微软雅黑\" color=\"#FFFFFF\">马</font><font face=\"微软雅黑\" color=\"#FF0000\">虎羊</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font color=\'#00ff00\' face=\'微软雅黑\'>&nbsp;116期:推荐四肖:</font><font face=\"微软雅黑\" color=\"#FF0000\">龙牛狗</font><font face=\"微软雅黑\" color=\"#FFFFFF\">马</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font color=\'#00ff00\' face=\'微软雅黑\'>&nbsp;116期:主攻八码:</font><font color=\'#FF0000\' face=\'微软雅黑\'>31.10.22.13.37.29.</font><font color=\'#FFFFFF\' face=\'微软雅黑\'>41</font><font color=\'#FF0000\' face=\'微软雅黑\'>.09</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>&nbsp;116期:经典单双:</font><font face=\"微软雅黑\" color=\"#FFFFFF\">单单单单</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>&nbsp;116期:平特一肖:</font><font face=\'微软雅黑\' color=\'#FFFFFF\'>龙龙龙龙</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>&nbsp;116期:平特一尾:</font><font face=\"微软雅黑\" color=\"#FFFFFF\">22222尾</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>&nbsp;116期:中特五尾:</font><font face=\"微软雅黑\" color=\"#FF0000\">0</font><font face=\"微软雅黑\" color=\"#FFFFFF\">1</font><font face=\"微软雅黑\" color=\"#FF0000\">279尾</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#ff9900\'>");
document.writeln("		<p align=\'center\'><font face=\'微软雅黑\'><b>第 114期:A级大公开;借钱拿高利贷也要大胆下注!</b></font></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font color=\'#00ff00\' face=\'微软雅黑\'>&nbsp;114期:推荐六肖:</font><font face=\"微软雅黑\" color=\"#FF0000\">牛</font><font face=\"微软雅黑\" color=\"#FFFFFF\">兔</font><font face=\"微软雅黑\" color=\"#FF0000\">蛇虎龙马</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font color=\'#00ff00\' face=\'微软雅黑\'>&nbsp;114期:推荐四肖:</font><font face=\"微软雅黑\" color=\"#FF0000\">牛</font><font face=\"微软雅黑\" color=\"#FFFFFF\">兔</font><font face=\"微软雅黑\" color=\"#FF0000\">蛇虎</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\' height=\"34\"><b><font color=\'#00ff00\' face=\'微软雅黑\'>");
document.writeln("		&nbsp;114期:推荐三肖:</font><font face=\"微软雅黑\" color=\"#FF0000\">牛</font><font face=\"微软雅黑\" color=\"#FFFFFF\">兔</font><font face=\"微软雅黑\" color=\"#FF0000\">蛇</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font color=\'#00ff00\' face=\'微软雅黑\'>&nbsp;114期:推荐二肖:</font><font face=\"微软雅黑\" color=\"#FF0000\">牛</font><font face=\"微软雅黑\" color=\"#FFFFFF\">兔</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font color=\'#00ff00\' face=\'微软雅黑\'>&nbsp;114期:主攻八码:</font><font color=\'#FF0000\' face=\'微软雅黑\'>22.</font><font color=\'#FFFFFF\' face=\'微软雅黑\'>08</font><font color=\'#FF0000\' face=\'微软雅黑\'>.32.30.21.33.07.29</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>&nbsp;114期:主攻三码:</font><font color=\'#FF0000\' face=\'微软雅黑\'>22.</font><font color=\'#FFFFFF\' face=\'微软雅黑\'>08</font><font color=\'#FF0000\' face=\'微软雅黑\'>.32</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>&nbsp;114期:经典单双:</font><font face=\"微软雅黑\" color=\"#FFFFFF\">双双双双</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>&nbsp;114期:平特一肖:</font><font face=\'微软雅黑\' color=\'#FFFFFF\'>鼠鼠鼠鼠</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>&nbsp;114期:平特一尾:</font><font face=\"微软雅黑\" color=\"#FFFFFF\">88888尾</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>&nbsp;114期:中特五尾:</font><font face=\"微软雅黑\" color=\"#FF0000\">2357</font><font face=\"微软雅黑\" color=\"#FFFFFF\">8</font><font face=\"微软雅黑\" color=\"#FF0000\">尾</font></b></td>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#ff9900\'>");
document.writeln("		<p align=\'center\'><font face=\'微软雅黑\'><b>第 113期:A级大公开;借钱拿高利贷也要大胆下注!</b></font></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font color=\'#00ff00\' face=\'微软雅黑\'>&nbsp;113期:推荐六肖:</font><font face=\"微软雅黑\" color=\"#FF0000\">马兔蛇</font><font face=\"微软雅黑\" color=\"#FFFFFF\">猴</font><font face=\"微软雅黑\" color=\"#FF0000\">龙狗</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font color=\'#00ff00\' face=\'微软雅黑\'>&nbsp;113期:推荐四肖:</font><font face=\"微软雅黑\" color=\"#FF0000\">马兔蛇</font><font face=\"微软雅黑\" color=\"#FFFFFF\">猴</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font color=\'#00ff00\' face=\'微软雅黑\'>&nbsp;113期:主攻八码:</font><font color=\'#FF0000\' face=\'微软雅黑\'>17.29.08.20.06.18.03.</font><font color=\'#FFFFFF\' face=\'微软雅黑\'>27</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>&nbsp;113期:经典单双:</font><font face=\"微软雅黑\" color=\"#FFFFFF\">单单单单</font></b></td>");
document.writeln("");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>&nbsp;113期:平特一尾:</font><font face=\"微软雅黑\" color=\"#FFFFFF\">44444尾</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>&nbsp;113期:中特五尾:</font><font face=\"微软雅黑\" color=\"#FF0000\">023</font><font face=\"微软雅黑\" color=\"#FFFFFF\">7</font><font face=\"微软雅黑\" color=\"#FF0000\">9尾</font></b></td>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#ff9900\'>");
document.writeln("		<p align=\'center\'><font face=\'微软雅黑\'><b>第 112期:A级大公开;借钱拿高利贷也要大胆下注!</b></font></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font color=\'#00ff00\' face=\'微软雅黑\'>&nbsp;112期:推荐六肖:</font><font face=\"微软雅黑\" color=\"#FF0000\">兔</font><font face=\"微软雅黑\" color=\"#FFFFFF\">龙</font><font face=\"微软雅黑\" color=\"#FF0000\">猴狗牛鼠</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font color=\'#00ff00\' face=\'微软雅黑\'>&nbsp;112期:推荐四肖:</font><font face=\"微软雅黑\" color=\"#FF0000\">兔</font><font face=\"微软雅黑\" color=\"#FFFFFF\">龙</font><font face=\"微软雅黑\" color=\"#FF0000\">猴狗</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\' height=\"34\"><b><font color=\'#00ff00\' face=\'微软雅黑\'>");
document.writeln("		&nbsp;112期:推荐三肖:</font><font face=\"微软雅黑\" color=\"#FF0000\">兔</font><font face=\"微软雅黑\" color=\"#FFFFFF\">龙</font><font face=\"微软雅黑\" color=\"#FF0000\">猴</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font color=\'#00ff00\' face=\'微软雅黑\'>&nbsp;112期:推荐二肖:</font><font face=\"微软雅黑\" color=\"#FF0000\">兔</font><font face=\"微软雅黑\" color=\"#FFFFFF\">龙</font></b></td>");
document.writeln("");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font color=\'#00ff00\' face=\'微软雅黑\'>&nbsp;112期:主攻八码:</font><font color=\'#FF0000\' face=\'微软雅黑\'>08.20.</font><font color=\'#FFFFFF\' face=\'微软雅黑\'>19</font><font color=\'#FF0000\' face=\'微软雅黑\'>.31.27.49.22.35</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>&nbsp;112期:主攻三码:</font><font color=\'#FF0000\' face=\'微软雅黑\'>08.20.</font><font color=\'#FFFFFF\' face=\'微软雅黑\'>19</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>&nbsp;112期:平特一尾:</font><font face=\"微软雅黑\" color=\"#FFFFFF\">99999尾</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>&nbsp;112期:中特五尾:</font><font face=\"微软雅黑\" color=\"#FF0000\">2348</font><font face=\"微软雅黑\" color=\"#FFFFFF\">9</font><font face=\"微软雅黑\" color=\"#FF0000\">尾</font></b></td>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#ff9900\'>");
document.writeln("		<p align=\'center\'><font face=\'微软雅黑\'><b>第 111期:A级大公开;借钱拿高利贷也要大胆下注!</b></font></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font color=\'#00ff00\' face=\'微软雅黑\'>&nbsp;111期:推荐六肖:</font><font face=\"微软雅黑\" color=\"#FF0000\">兔鸡蛇猴</font><font face=\"微软雅黑\" color=\"#FFFFFF\">羊</font><font face=\"微软雅黑\" color=\"#FF0000\">鼠</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>&nbsp;111期:经典单双:</font><font face=\"微软雅黑\" color=\"#FFFFFF\">双双双双</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>&nbsp;111期:平特一肖:</font><font face=\'微软雅黑\' color=\'#FFFFFF\'>鼠鼠鼠鼠</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>&nbsp;111期:平特一尾:</font><font face=\"微软雅黑\" color=\"#FFFFFF\">66666尾</font></b></td>");
document.writeln("									</tr>");
document.writeln("");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#ff9900\'>");
document.writeln("		<p align=\'center\'><font face=\'微软雅黑\'><b>第 109期:A级大公开;借钱拿高利贷也要大胆下注!</b></font></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font color=\'#00ff00\' face=\'微软雅黑\'>&nbsp;109期:推荐六肖:</font><font face=\"微软雅黑\" color=\"#FF0000\">兔鼠蛇龙马</font><font face=\"微软雅黑\" color=\"#FFFFFF\">羊</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>&nbsp;109期:经典单双:</font><font face=\"微软雅黑\" color=\"#FFFFFF\">双双双双</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>&nbsp;109期:平特一肖:</font><font face=\'微软雅黑\' color=\'#FFFFFF\'>兔兔兔兔</font></b></td>");
document.writeln("");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>&nbsp;109期:中特五尾:</font><font face=\"微软雅黑\" color=\"#FFFFFF\">4</font><font face=\"微软雅黑\" color=\"#FF0000\">5789尾</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#ff9900\'>");
document.writeln("		<p align=\'center\'><font face=\'微软雅黑\'><b>第 108期:A级大公开;借钱拿高利贷也要大胆下注!</b></font></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font color=\'#00ff00\' face=\'微软雅黑\'>&nbsp;108期:推荐六肖:</font><font color=\'#FF0000\' face=\'微软雅黑\'>兔猴羊鸡</font><font color=\'#FFFFFF\' face=\'微软雅黑\'>蛇</font><font color=\'#FF0000\' face=\'微软雅黑\'>鼠</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>&nbsp;108期:经典单双:</font><font face=\"微软雅黑\" color=\"#FFFFFF\">双双双双</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>&nbsp;108期:平特一肖:</font><font face=\'微软雅黑\' color=\'#FFFFFF\'>兔兔兔兔</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>&nbsp;108期:平特一尾:</font><font face=\"微软雅黑\" color=\"#FFFFFF\">33333尾</font></b></td>");
document.writeln("									");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#ff9900\'>");
document.writeln("		<p align=\'center\'><font face=\'微软雅黑\'><b>第 106期:A级大公开;借钱拿高利贷也要大胆下注!</b></font></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font color=\'#00ff00\' face=\'微软雅黑\'>&nbsp;106期:推荐六肖:</font><font face=\"微软雅黑\" color=\"#FF0000\">龙猴兔</font><font face=\"微软雅黑\" color=\"#FFFFFF\">鸡</font><font face=\"微软雅黑\" color=\"#FF0000\">猪羊</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font color=\'#00ff00\' face=\'微软雅黑\'>&nbsp;106期:推荐四肖:</font><font face=\"微软雅黑\" color=\"#FF0000\">龙猴兔</font><font face=\"微软雅黑\" color=\"#FFFFFF\">鸡</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#ff9900\'>");
document.writeln("		<p align=\'center\'><font face=\'微软雅黑\'><b>第104期:A级大公开;借钱拿高利贷也要大胆下注!</b></font></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font color=\'#00ff00\' face=\'微软雅黑\'>104期:推荐六肖:</font><font face=\"微软雅黑\" color=\"#FF0000\">猪兔龙</font><font face=\"微软雅黑\" color=\"#FFFFFF\">鼠</font><font face=\"微软雅黑\" color=\"#FF0000\">猴牛</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font color=\'#00ff00\' face=\'微软雅黑\'>104期:推荐四肖:</font><font face=\"微软雅黑\" color=\"#FF0000\">猪兔龙</font><font face=\"微软雅黑\" color=\"#FFFFFF\">鼠</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>104期:平特一肖:</font><font face=\'微软雅黑\' color=\'#FFFFFF\'>牛牛牛牛</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>104期:平特一尾:</font><font face=\"微软雅黑\" color=\"#FFFFFF\">44444尾</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>104期:中特五尾:</font><font face=\"微软雅黑\" color=\"#FF0000\">123</font><font face=\"微软雅黑\" color=\"#FFFFFF\">5</font><font face=\"微软雅黑\" color=\"#FF0000\">6尾</font></b></td>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#ff9900\'>");
document.writeln("		<p align=\'center\'><font face=\'微软雅黑\'><b>第102期:A级大公开;借钱拿高利贷也要大胆下注!</b></font></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font color=\'#00ff00\' face=\'微软雅黑\'>102期:推荐六肖:</font><font face=\"微软雅黑\" color=\"#FF0000\">兔龙马鸡</font><font face=\"微软雅黑\" color=\"#FFFFFF\">虎</font><font face=\"微软雅黑\" color=\"#FF0000\">猪</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>102期:经典单双:</font><font face=\"微软雅黑\" color=\"#FFFFFF\">单单单单</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>102期:平特一肖:</font><font face=\'微软雅黑\' color=\'#FFFFFF\'>龙龙龙龙</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>102期:平特一尾:</font><font face=\"微软雅黑\" color=\"#FFFFFF\">66666尾</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#ff9900\'>");
document.writeln("		<p align=\'center\'><font face=\'微软雅黑\'><b>第101期:A级大公开;借钱拿高利贷也要大胆下注!</b></font></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font color=\'#00ff00\' face=\'微软雅黑\'>101期:推荐六肖:</font><font face=\"微软雅黑\" color=\"#FF0000\">虎猴龙</font><font face=\"微软雅黑\" color=\"#FFFFFF\">鼠</font><font face=\"微软雅黑\" color=\"#FF0000\">兔猪</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font color=\'#00ff00\' face=\'微软雅黑\'>101期:推荐四肖:</font><font face=\"微软雅黑\" color=\"#FF0000\">虎猴龙</font><font face=\"微软雅黑\" color=\"#FFFFFF\">鼠</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>101期:经典单双:</font><font face=\"微软雅黑\" color=\"#FFFFFF\">单单单单</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>101期:平特一肖:</font><font face=\'微软雅黑\' color=\'#FFFFFF\'>虎虎虎虎</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>101期:平特一尾:</font><font face=\"微软雅黑\" color=\"#FFFFFF\">99999尾</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>101期:中特五尾:</font><font face=\"微软雅黑\" color=\"#FF0000\">15</font><font face=\"微软雅黑\" color=\"#FFFFFF\">7</font><font face=\"微软雅黑\" color=\"#FF0000\">89尾</font></b></td>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#ff9900\'>");
document.writeln("		<p align=\'center\'><font face=\'微软雅黑\'><b>第100期:A级大公开;借钱拿高利贷也要大胆下注!</b></font></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font color=\'#00ff00\' face=\'微软雅黑\'>100期:推荐六肖:</font><font face=\"微软雅黑\" color=\"#FF0000\">马龙兔猪</font><font face=\"微软雅黑\" color=\"#FFFFFF\">狗</font><font face=\"微软雅黑\" color=\"#FF0000\">虎</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\"微软雅黑\" color=\"#00FF00\">100期:经典单双:</font><font face=\"微软雅黑\" color=\"#FFFFFF\">单单单单</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\"微软雅黑\" color=\"#00FF00\">100期:平特一尾:</font><font face=\"微软雅黑\" color=\"#FFFFFF\">77777尾</font></b></td>");
document.writeln("									</tr>");
document.writeln("									");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#ff9900\'>");
document.writeln("		<p align=\'center\'><font face=\'微软雅黑\'><b>第098期:A级大公开;借钱拿高利贷也要大胆下注!</b></font></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font color=\'#00ff00\' face=\'微软雅黑\'>098期:推荐六肖:</font><font face=\"微软雅黑\" color=\"#FF0000\">羊鼠兔鸡</font><font face=\"微软雅黑\" color=\"#FFFFFF\">狗</font><font face=\"微软雅黑\" color=\"#FF0000\">虎</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>098期:平特一肖:</font><font face=\'微软雅黑\' color=\'#FFFFFF\'>狗狗狗狗</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>098期:平特一尾:</font><font face=\"微软雅黑\" color=\"#FFFFFF\">55555尾</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>098期:中特五尾:</font><font face=\"微软雅黑\" color=\"#FF0000\">1</font><font face=\"微软雅黑\" color=\"#FFFFFF\">3</font><font face=\"微软雅黑\" color=\"#FF0000\">578尾</font></b></td>");
document.writeln("									</tr>");
document.writeln("	");
document.writeln("	");
document.writeln("									");
document.writeln("									");
document.writeln("	");
document.writeln("");
