document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta http-equiv=\'Content-Language\' content=\'zh-cn\'>");
document.writeln("<meta http-equiv=\'Content-Type\' content=\'text/html; charset=utf-8\'>");
document.writeln("<title>六肖八码</title>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("<table width=\'100%\' id=\'table23\' bordercolorlight=\'#ffffff\' bordercolordark=\'#ffffff\' style=\'font: 21px/28px tahoma, 微软雅黑, 宋体, arial, georgia, verdana, helvetica, sans-serif; color: rgb(68, 68, 68); text-transform: none; text-indent: 0px; letter-spacing: normal; word-spacing: 0px; white-space: normal; border-collapse: collapse; border-spacing: 0px; widows: 1; -webkit-text-stroke-width: 0px;\' bgcolor=\'#ffffff\' border=\'0\' cellspacing=\'0\' cellpadding=\'0\'>");
document.writeln("		<!-----------------开始复制-------------------------------->");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#ff9900\'>");
document.writeln("		<p align=\'center\'><font face=\'微软雅黑\'><b>第 107期:A级大公开;借钱拿高利贷也要大胆下注!</b></font></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font color=\'#00ff00\' face=\'微软雅黑\'>&nbsp;107期:推荐六肖:</font><font face=\"微软雅黑\" color=\"#FF0000\">加码王微信，免费领取⒈肖中特！</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font color=\'#00ff00\' face=\'微软雅黑\'>&nbsp;107期:推荐四肖:</font><font face=\"微软雅黑\" color=\"#FF0000\">微信：<span style=\"background-color: #FFFF00\">38890562</span></font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\' height=\"34\"><b><font color=\'#00ff00\' face=\'微软雅黑\'>");
document.writeln("		&nbsp;107期:推荐三肖:</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font color=\'#00ff00\' face=\'微软雅黑\'>&nbsp;107期:推荐二肖:</font><font face=\"微软雅黑\" color=\"#FF0000\">加码王微信，免费领取⒈肖中特！</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font color=\'#00ff00\' face=\'微软雅黑\'>&nbsp;107期:推荐一肖:</font><font face=\"微软雅黑\" color=\"#FF0000\">微信：<span style=\"background-color: #FFFF00\">38890562</span></font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font color=\'#00ff00\' face=\'微软雅黑\'>&nbsp;107期:主攻八码:</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>&nbsp;107期:主攻三码:</font><font face=\"微软雅黑\" color=\"#FF0000\">加码王微信，免费领取⒈肖中特！</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>&nbsp;107期:经典单双:</font><font face=\"微软雅黑\" color=\"#FF0000\">微信：<span style=\"background-color: #FFFF00\">38890562</span></font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>&nbsp;107期:平特一肖:</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>&nbsp;107期:平特一尾:</font><font face=\"微软雅黑\" color=\"#FF0000\">码王微信，免费领取⒈肖中特！</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>&nbsp;107期:中特五尾:</font><font face=\"微软雅黑\" color=\"#FF0000\">微信：<span style=\"background-color: #FFFF00\">38890562</span></font></b></td>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#ff9900\'>");
document.writeln("		<p align=\'center\'><font face=\'微软雅黑\'><b>第 106期:A级大公开;借钱拿高利贷也要大胆下注!</b></font></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font color=\'#00ff00\' face=\'微软雅黑\'>&nbsp;106期:推荐六肖:</font><font face=\"微软雅黑\" color=\"#FF0000\">龙猴兔</font><font face=\"微软雅黑\" color=\"#FFFFFF\">鸡</font><font face=\"微软雅黑\" color=\"#FF0000\">猪羊</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font color=\'#00ff00\' face=\'微软雅黑\'>&nbsp;106期:推荐四肖:</font><font face=\"微软雅黑\" color=\"#FF0000\">龙猴兔</font><font face=\"微软雅黑\" color=\"#FFFFFF\">鸡</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#ff9900\'>");
document.writeln("		<p align=\'center\'><font face=\'微软雅黑\'><b>第104期:A级大公开;借钱拿高利贷也要大胆下注!</b></font></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font color=\'#00ff00\' face=\'微软雅黑\'>104期:推荐六肖:</font><font face=\"微软雅黑\" color=\"#FF0000\">猪兔龙</font><font face=\"微软雅黑\" color=\"#FFFFFF\">鼠</font><font face=\"微软雅黑\" color=\"#FF0000\">猴牛</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font color=\'#00ff00\' face=\'微软雅黑\'>104期:推荐四肖:</font><font face=\"微软雅黑\" color=\"#FF0000\">猪兔龙</font><font face=\"微软雅黑\" color=\"#FFFFFF\">鼠</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>104期:平特一肖:</font><font face=\'微软雅黑\' color=\'#FFFFFF\'>牛牛牛牛</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>104期:平特一尾:</font><font face=\"微软雅黑\" color=\"#FFFFFF\">44444尾</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>104期:中特五尾:</font><font face=\"微软雅黑\" color=\"#FF0000\">123</font><font face=\"微软雅黑\" color=\"#FFFFFF\">5</font><font face=\"微软雅黑\" color=\"#FF0000\">6尾</font></b></td>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#ff9900\'>");
document.writeln("		<p align=\'center\'><font face=\'微软雅黑\'><b>第102期:A级大公开;借钱拿高利贷也要大胆下注!</b></font></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font color=\'#00ff00\' face=\'微软雅黑\'>102期:推荐六肖:</font><font face=\"微软雅黑\" color=\"#FF0000\">兔龙马鸡</font><font face=\"微软雅黑\" color=\"#FFFFFF\">虎</font><font face=\"微软雅黑\" color=\"#FF0000\">猪</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>102期:经典单双:</font><font face=\"微软雅黑\" color=\"#FFFFFF\">单单单单</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>102期:平特一肖:</font><font face=\'微软雅黑\' color=\'#FFFFFF\'>龙龙龙龙</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>102期:平特一尾:</font><font face=\"微软雅黑\" color=\"#FFFFFF\">66666尾</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#ff9900\'>");
document.writeln("		<p align=\'center\'><font face=\'微软雅黑\'><b>第101期:A级大公开;借钱拿高利贷也要大胆下注!</b></font></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font color=\'#00ff00\' face=\'微软雅黑\'>101期:推荐六肖:</font><font face=\"微软雅黑\" color=\"#FF0000\">虎猴龙</font><font face=\"微软雅黑\" color=\"#FFFFFF\">鼠</font><font face=\"微软雅黑\" color=\"#FF0000\">兔猪</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font color=\'#00ff00\' face=\'微软雅黑\'>101期:推荐四肖:</font><font face=\"微软雅黑\" color=\"#FF0000\">虎猴龙</font><font face=\"微软雅黑\" color=\"#FFFFFF\">鼠</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>101期:经典单双:</font><font face=\"微软雅黑\" color=\"#FFFFFF\">单单单单</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>101期:平特一肖:</font><font face=\'微软雅黑\' color=\'#FFFFFF\'>虎虎虎虎</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>101期:平特一尾:</font><font face=\"微软雅黑\" color=\"#FFFFFF\">99999尾</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>101期:中特五尾:</font><font face=\"微软雅黑\" color=\"#FF0000\">15</font><font face=\"微软雅黑\" color=\"#FFFFFF\">7</font><font face=\"微软雅黑\" color=\"#FF0000\">89尾</font></b></td>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#ff9900\'>");
document.writeln("		<p align=\'center\'><font face=\'微软雅黑\'><b>第100期:A级大公开;借钱拿高利贷也要大胆下注!</b></font></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font color=\'#00ff00\' face=\'微软雅黑\'>100期:推荐六肖:</font><font face=\"微软雅黑\" color=\"#FF0000\">马龙兔猪</font><font face=\"微软雅黑\" color=\"#FFFFFF\">狗</font><font face=\"微软雅黑\" color=\"#FF0000\">虎</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\"微软雅黑\" color=\"#00FF00\">100期:经典单双:</font><font face=\"微软雅黑\" color=\"#FFFFFF\">单单单单</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\"微软雅黑\" color=\"#00FF00\">100期:平特一尾:</font><font face=\"微软雅黑\" color=\"#FFFFFF\">77777尾</font></b></td>");
document.writeln("									</tr>");
document.writeln("									");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#ff9900\'>");
document.writeln("		<p align=\'center\'><font face=\'微软雅黑\'><b>第098期:A级大公开;借钱拿高利贷也要大胆下注!</b></font></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font color=\'#00ff00\' face=\'微软雅黑\'>098期:推荐六肖:</font><font face=\"微软雅黑\" color=\"#FF0000\">羊鼠兔鸡</font><font face=\"微软雅黑\" color=\"#FFFFFF\">狗</font><font face=\"微软雅黑\" color=\"#FF0000\">虎</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>098期:平特一肖:</font><font face=\'微软雅黑\' color=\'#FFFFFF\'>狗狗狗狗</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>098期:平特一尾:</font><font face=\"微软雅黑\" color=\"#FFFFFF\">55555尾</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>098期:中特五尾:</font><font face=\"微软雅黑\" color=\"#FF0000\">1</font><font face=\"微软雅黑\" color=\"#FFFFFF\">3</font><font face=\"微软雅黑\" color=\"#FF0000\">578尾</font></b></td>");
document.writeln("									</tr>");
document.writeln("	<table width=\'100%\' id=\'table22\' bordercolorlight=\'#ffffff\' bordercolordark=\'#ffffff\' style=\'font: 21px/28px tahoma, 微软雅黑, 宋体, arial, georgia, verdana, helvetica, sans-serif; color: rgb(68, 68, 68); text-transform: none; text-indent: 0px; letter-spacing: normal; word-spacing: 0px; white-space: normal; border-collapse: collapse; border-spacing: 0px; widows: 1; -webkit-text-stroke-width: 0px;\' bgcolor=\'#ffffff\' border=\'0\' cellspacing=\'0\' cellpadding=\'0\'>");
document.writeln("		<!-----------------开始复制-------------------------------->");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#ff9900\'>");
document.writeln("		<p align=\'center\'><font face=\'微软雅黑\'><b>第097期:A级大公开;借钱拿高利贷也要大胆下注!</b></font></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font color=\'#00ff00\' face=\'微软雅黑\'>097期:推荐六肖:</font><font face=\"微软雅黑\" color=\"#FF0000\">鼠马</font><font face=\"微软雅黑\" color=\"#FFFFFF\">鸡</font><font face=\"微软雅黑\" color=\"#FF0000\">狗虎猴</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font color=\'#00ff00\' face=\'微软雅黑\'>097期:推荐四肖:</font><font face=\"微软雅黑\" color=\"#FF0000\">鼠马</font><font face=\"微软雅黑\" color=\"#FFFFFF\">鸡</font><font face=\"微软雅黑\" color=\"#FF0000\">狗</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\' height=\"34\"><b><font color=\'#00ff00\' face=\'微软雅黑\'>");
document.writeln("		097期:推荐三肖:</font><font face=\"微软雅黑\" color=\"#FF0000\">鼠马</font><font face=\"微软雅黑\" color=\"#FFFFFF\">鸡</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>097期:平特一肖:</font><font face=\'微软雅黑\' color=\'#FFFFFF\'>鸡鸡鸡鸡</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<table width=\'100%\' id=\'table2\' bordercolorlight=\'#ffffff\' bordercolordark=\'#ffffff\' style=\'font: 21px/28px tahoma, 微软雅黑, 宋体, arial, georgia, verdana, helvetica, sans-serif; color: rgb(68, 68, 68); text-transform: none; text-indent: 0px; letter-spacing: normal; word-spacing: 0px; white-space: normal; border-collapse: collapse; border-spacing: 0px; widows: 1; -webkit-text-stroke-width: 0px;\' bgcolor=\'#ffffff\' border=\'0\' cellspacing=\'0\' cellpadding=\'0\'>");
document.writeln("		");
document.writeln("       								<!-----------------开始复制-------------------------------->");
document.writeln("		");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#ff9900\'>");
document.writeln("		<p align=\'center\'><font face=\'微软雅黑\'><b>第095期:A级大公开;借钱拿高利贷也要大胆下注!</b></font></td>");
document.writeln("									</tr>");
document.writeln("									<table width=\'100%\' id=\'table3\' bordercolorlight=\'#ffffff\' bordercolordark=\'#ffffff\' style=\'font: 21px/28px tahoma, 微软雅黑, 宋体, arial, georgia, verdana, helvetica, sans-serif; color: rgb(68, 68, 68); text-transform: none; text-indent: 0px; letter-spacing: normal; word-spacing: 0px; white-space: normal; border-collapse: collapse; border-spacing: 0px; widows: 1; -webkit-text-stroke-width: 0px;\' bgcolor=\'#ffffff\' border=\'0\' cellspacing=\'0\' cellpadding=\'0\'>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font color=\'#00ff00\' face=\'微软雅黑\'>095期:推荐六肖:</font><font face=\"微软雅黑\" color=\"#FF0000\">蛇鸡</font><font face=\"微软雅黑\" color=\"#FFFFFF\">牛</font><font face=\"微软雅黑\" color=\"#FF0000\">虎猴马</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font color=\'#00ff00\' face=\'微软雅黑\'>095期:推荐四肖:</font><font face=\"微软雅黑\" color=\"#FF0000\">蛇鸡</font><font face=\"微软雅黑\" color=\"#FFFFFF\">牛</font><font face=\"微软雅黑\" color=\"#FF0000\">虎猴</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\' height=\"34\"><b><font color=\'#00ff00\' face=\'微软雅黑\'>");
document.writeln("		095期:推荐三肖:</font><font face=\"微软雅黑\" color=\"#FF0000\">蛇鸡</font><font face=\"微软雅黑\" color=\"#FFFFFF\">牛</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>095期:经典单双:</font><font face=\"微软雅黑\" color=\"#FFFFFF\">双双双双</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>095期:平特一肖:</font><font face=\'微软雅黑\' color=\'#FFFFFF\'>牛牛牛牛</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>095期:中特五尾:</font><font face=\"微软雅黑\" color=\"#FF0000\">012</font><font face=\"微软雅黑\" color=\"#FFFFFF\">4</font><font face=\"微软雅黑\" color=\"#FF0000\">6尾</font></b></td>");
document.writeln("									</tr>");
document.writeln("	<table width=\'100%\' id=\'table2\' bordercolorlight=\'#ffffff\' bordercolordark=\'#ffffff\' style=\'font: 21px/28px tahoma, 微软雅黑, 宋体, arial, georgia, verdana, helvetica, sans-serif; color: rgb(68, 68, 68); text-transform: none; text-indent: 0px; letter-spacing: normal; word-spacing: 0px; white-space: normal; border-collapse: collapse; border-spacing: 0px; widows: 1; -webkit-text-stroke-width: 0px;\' bgcolor=\'#ffffff\' border=\'0\' cellspacing=\'0\' cellpadding=\'0\'>");
document.writeln("		");
document.writeln("<!-----------------开始复制-------------------------------->	");
document.writeln("				<tr>");
document.writeln("		<td bgcolor=\'#ff9900\'>");
document.writeln("		<p align=\'center\'><font face=\'微软雅黑\'><b>第090期:A级大公开;借钱拿高利贷也要大胆下注!</b></font></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font color=\'#00ff00\' face=\'微软雅黑\'>090期:推荐六肖:</font><font face=\"微软雅黑\" color=\"#FF0000\">龙鸡猪</font><font face=\"微软雅黑\" color=\"#FFFFFF\">狗</font><font face=\"微软雅黑\" color=\"#FF0000\">虎兔</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font color=\'#00ff00\' face=\'微软雅黑\'>090期:推荐四肖:</font><font face=\"微软雅黑\" color=\"#FF0000\">龙鸡猪</font><font face=\"微软雅黑\" color=\"#FFFFFF\">狗</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>090期:经典单双:</font><font face=\"微软雅黑\" color=\"#FFFFFF\">单单单单</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>090期:中特五尾:</font><font face=\"微软雅黑\" color=\"#FF0000\">145</font><font face=\"微软雅黑\" color=\"#FFFFFF\">7</font><font face=\"微软雅黑\" color=\"#FF0000\">8尾</font></b></td>");
document.writeln("									</tr>");
document.writeln("	<table width=\'100%\' id=\'table21\' bordercolorlight=\'#ffffff\' bordercolordark=\'#ffffff\' style=\'font: 21px/28px tahoma, 微软雅黑, 宋体, arial, georgia, verdana, helvetica, sans-serif; color: rgb(68, 68, 68); text-transform: none; text-indent: 0px; letter-spacing: normal; word-spacing: 0px; white-space: normal; border-collapse: collapse; border-spacing: 0px; widows: 1; -webkit-text-stroke-width: 0px;\' bgcolor=\'#ffffff\' border=\'0\' cellspacing=\'0\' cellpadding=\'0\'>");
document.writeln("		");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#ff9900\'>");
document.writeln("		<p align=\'center\'><font face=\'微软雅黑\'><b>第088期:A级大公开;借钱拿高利贷也要大胆下注!</b></font></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font color=\'#00ff00\' face=\'微软雅黑\'>088期:推荐六肖:</font><font face=\"微软雅黑\" color=\"#FF0000\">马</font><font face=\"微软雅黑\" color=\"#FFFFFF\">猪</font><font face=\"微软雅黑\" color=\"#FF0000\">猴龙狗牛</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font color=\'#00ff00\' face=\'微软雅黑\'>088期:推荐四肖:</font><font face=\"微软雅黑\" color=\"#FF0000\">马</font><font face=\"微软雅黑\" color=\"#FFFFFF\">猪</font><font face=\"微软雅黑\" color=\"#FF0000\">猴龙</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\' height=\"34\"><b><font color=\'#00ff00\' face=\'微软雅黑\'>");
document.writeln("		088期:推荐三肖:</font><font face=\"微软雅黑\" color=\"#FF0000\">马</font><font face=\"微软雅黑\" color=\"#FFFFFF\">猪</font><font face=\"微软雅黑\" color=\"#FF0000\">猴龙</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font color=\'#00ff00\' face=\'微软雅黑\'>088期:推荐二肖:</font><font face=\"微软雅黑\" color=\"#FF0000\">马</font><font face=\"微软雅黑\" color=\"#FFFFFF\">猪</font><font face=\"微软雅黑\" color=\"#FF0000\">猴</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font color=\'#00ff00\' face=\'微软雅黑\'>088期:主攻八码:</font><font color=\'#FF0000\' face=\'微软雅黑\'>29.17.24.36.15.31.25.</font><font color=\'#FFFFFF\' face=\'微软雅黑\'>12</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>088期:平特一肖:</font><font face=\'微软雅黑\' color=\'#FFFFFF\'>虎虎虎虎</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>088期:平特一尾:</font><font face=\"微软雅黑\" color=\"#FFFFFF\">99999尾</font></b></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("		<td bgcolor=\'#000000\'><b><font face=\'微软雅黑\' color=\'#00FF00\'>088期:中特五尾:</font><font face=\"微软雅黑\" color=\"#FF0000\">1</font><font face=\"微软雅黑\" color=\"#FFFFFF\">2</font><font face=\"微软雅黑\" color=\"#FF0000\">456尾</font></b></td>");
document.writeln("									</tr>");
document.writeln("	");
document.writeln("									");
document.writeln("									");
document.writeln("	");
document.writeln("");
