document.writeln("<html>");
document.writeln("");
document.writeln("<head>");
document.writeln("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\">");
document.writeln("<title>000082</title>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("");
document.writeln("<table border=\'1\' width=\'100%\' bordercolor=\'#CAE2F8\' height=\'46\' style=\'border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: rgb(225, 225, 225); border-collapse: collapse; color: rgb(51, 51, 51); font-size: 24px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 36px; orphans: auto; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; font-family: Simsun;\'>");
document.writeln("	<!-----------------生活幽默-------------------------------->");
document.writeln("	<tr style=\'border: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<td bgcolor=\'#FF9900\' height=\'46\' width=\'97%\' style=\'border: 1px solid rgb(225, 225, 225); padding: 3px 2px; word-break: break-all; font-size: 12px; color: rgb(0, 0, 0);\'>");
document.writeln("		<p style=\"text-align: center\">");
document.writeln("		<span style=\"color: rgb(0, 0, 0); font-family: 微软雅黑; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: -webkit-center; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 153, 0)\">");
document.writeln("		<font size=\"3\">800000000.cc</font></span><span style=\"background-color: #FF9900\"><font size=\"3\"><span style=\"font-family: 微软雅黑\">生活幽默解玄机-经典原创</span></font></span></td>");
document.writeln("	</tr>");
document.writeln("	</table><table border=\'1\' width=\'100%\' bordercolor=\'#CAE2F8\' height=\'159\' style=\'border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: rgb(225, 225, 225); border-collapse: collapse; color: rgb(51, 51, 51); font-size: 24px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 36px; orphans: auto; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; font-family: Simsun;\'>");
document.writeln("	<tr style=\'border: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<td bgcolor=\'#ffffff\' height=\'21\' width=\'99%\' style=\'word-break: break-all; font-size: 12px; color: rgb(0, 0, 0); border: 1px solid rgb(225, 225, 225); padding-left: 2px; padding-right: 2px; padding-top: 3px; padding-bottom: 3px\'>");
document.writeln("		<span style=\"color: rgb(51, 51, 51); font-family: 微软雅黑; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 255, 255)\">");
document.writeln("		107期：两夫妻正在吵架，老丈人碰巧过来，三人面面相觑，场面十分尴尬，夫正不知道该怎么说话，妻子手机突然响了，她直接按了免提，竟然是岳母打来的，琴子，你爸有没有去你家？我刚跟他吵了一架，老家伙没吵赢，离家出走了！</span></tr>");
document.writeln("	<tr style=\'border: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<td bgcolor=\'#ffffff\' height=\'21\' width=\'99%\' style=\'word-break: break-all; font-size: 12px; color: rgb(0, 0, 0); border: 1px solid rgb(225, 225, 225); padding-left: 2px; padding-right: 2px; padding-top: 3px; padding-bottom: 3px\'>");
document.writeln("		<p align=\'center\' style=\'margin: 0px; padding: 0px\'>");
document.writeln("		<font face=\'微软雅黑\' style=\'font-size: 11pt\'>解：本站生活幽默通俗易懂，笑中有意，其味无穷。</font></td>");
document.writeln("	</tr>	");
document.writeln("	");
document.writeln("");
document.writeln("	<!-----------------生活幽默-------------------------------->	<!-----------------生活幽默-------------------------------->");
document.writeln("	<tr style=\'border: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<td bgcolor=\'#FF9900\' height=\'46\' width=\'97%\' style=\'border: 1px solid rgb(225, 225, 225); padding: 3px 2px; word-break: break-all; font-size: 12px; color: rgb(0, 0, 0);\'>");
document.writeln("		<p style=\"text-align: center\">");
document.writeln("		<span style=\"color: rgb(0, 0, 0); font-family: 微软雅黑; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: -webkit-center; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 153, 0)\">");
document.writeln("		<font size=\"3\">800000000.cc</font></span><span style=\"background-color: #FF9900\"><font size=\"3\"><span style=\"font-family: 微软雅黑\">生活幽默解玄机-经典原创</span></font></span></td>");
document.writeln("	</tr>");
document.writeln("	</table><table border=\'1\' width=\'100%\' bordercolor=\'#CAE2F8\' height=\'159\' style=\'border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: rgb(225, 225, 225); border-collapse: collapse; color: rgb(51, 51, 51); font-size: 24px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 36px; orphans: auto; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; font-family: Simsun;\'>");
document.writeln("	<tr style=\'border: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<td bgcolor=\'#ffffff\' height=\'21\' width=\'99%\' style=\'word-break: break-all; font-size: 12px; color: rgb(0, 0, 0); border: 1px solid rgb(225, 225, 225); padding-left: 2px; padding-right: 2px; padding-top: 3px; padding-bottom: 3px\'>");
document.writeln("		<span style=\"color: rgb(51, 51, 51); font-family: 微软雅黑; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 255, 255)\">");
document.writeln("		106期：男子每天要打牌，并且总要到半夜三更才回家。有一次，他老婆极为愤怒地对他说：我告诉你，若是你再让我等的话，我就要把男的带回家睡觉了，男子：随意你啦！不过我也正告你，可别拉走我的牌友。男子每天要打牌，并且总要到半夜三更才回家。有一次，他老婆极为愤怒地对他说：我告诉你，若是你再让我等的话，我就要把男的带回家睡觉了，男子：随意你啦！不过我也正告你，可别拉走我的牌友。</span></tr>");
document.writeln("	<tr style=\'border: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<td bgcolor=\'#ffffff\' height=\'21\' width=\'99%\' style=\'word-break: break-all; font-size: 12px; color: rgb(0, 0, 0); border: 1px solid rgb(225, 225, 225); padding-left: 2px; padding-right: 2px; padding-top: 3px; padding-bottom: 3px\'>");
document.writeln("		<p align=\'center\' style=\'margin: 0px; padding: 0px\'>");
document.writeln("		<font face=\'微软雅黑\' style=\'font-size: 11pt\'>解：文中讲总要到半夜三更才回家，指明夜肖中的家肖鸡狗猪牛，要把男的带回家睡觉了言外之意符合生肖为鸡，开鸡肖</font></td>");
document.writeln("	</tr>	");
document.writeln("	");
document.writeln("");
document.writeln("	<!-----------------生活幽默-------------------------------->	<!-----------------生活幽默-------------------------------->");
document.writeln("	<tr style=\'border: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<td bgcolor=\'#FF9900\' height=\'46\' width=\'97%\' style=\'border: 1px solid rgb(225, 225, 225); padding: 3px 2px; word-break: break-all; font-size: 12px; color: rgb(0, 0, 0);\'>");
document.writeln("		<p style=\"text-align: center\">");
document.writeln("		<span style=\"color: rgb(0, 0, 0); font-family: 微软雅黑; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: -webkit-center; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 153, 0)\">");
document.writeln("		<font size=\"3\">800000000.cc</font></span><span style=\"background-color: #FF9900\"><font size=\"3\"><span style=\"font-family: 微软雅黑\">生活幽默解玄机-经典原创</span></font></span></td>");
document.writeln("	</tr>");
document.writeln("	</table><table border=\'1\' width=\'100%\' bordercolor=\'#CAE2F8\' height=\'159\' style=\'border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: rgb(225, 225, 225); border-collapse: collapse; color: rgb(51, 51, 51); font-size: 24px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 36px; orphans: auto; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; font-family: Simsun;\'>");
document.writeln("	<tr style=\'border: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<td bgcolor=\'#ffffff\' height=\'21\' width=\'99%\' style=\'word-break: break-all; font-size: 12px; color: rgb(0, 0, 0); border: 1px solid rgb(225, 225, 225); padding-left: 2px; padding-right: 2px; padding-top: 3px; padding-bottom: 3px\'>");
document.writeln("		<span style=\"color: rgb(51, 51, 51); font-family: 微软雅黑; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 255, 255)\">");
document.writeln("		105期：</span><span style=\"font-family: 微软雅黑; font-size: 14px; color: #333333; background-color: #FFFFFF\">凌晨三点，医生家电话响了。喂电话那头很慌乱：医生，我们的宝宝刚吞下了一个避孕套。医生说：赶快来医院，十分钟后在医院碰头。穿好衣服准备出门，电话又响了。喂？电话那头传来平静的声音：没事了医生，我们又找到了一个，不用麻烦您了。</span></tr>");
document.writeln("	<tr style=\'border: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<td bgcolor=\'#ffffff\' height=\'21\' width=\'99%\' style=\'word-break: break-all; font-size: 12px; color: rgb(0, 0, 0); border: 1px solid rgb(225, 225, 225); padding-left: 2px; padding-right: 2px; padding-top: 3px; padding-bottom: 3px\'>");
document.writeln("		<p align=\'center\' style=\'margin: 0px; padding: 0px\'>");
document.writeln("		<font face=\'微软雅黑\' style=\'font-size: 11pt\'>解：文中医生家电话响指家肖，赶快来医院说明家肖中速度跑得快的马，本期开马肖</font></td>");
document.writeln("	</tr>	");
document.writeln("	");
document.writeln("");
document.writeln("	<!-----------------生活幽默-------------------------------->");
document.writeln("	<tr style=\'border: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<td bgcolor=\'#FF9900\' height=\'46\' width=\'97%\' style=\'border: 1px solid rgb(225, 225, 225); padding: 3px 2px; word-break: break-all; font-size: 12px; color: rgb(0, 0, 0);\'>");
document.writeln("		<p style=\"text-align: center\">");
document.writeln("		<span style=\"color: rgb(0, 0, 0); font-family: 微软雅黑; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: -webkit-center; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 153, 0)\">");
document.writeln("		<font size=\"3\">800000000.cc</font></span><span style=\"background-color: #FF9900\"><font size=\"3\"><span style=\"font-family: 微软雅黑\">生活幽默解玄机-经典原创</span></font></span></td>");
document.writeln("	</tr>");
document.writeln("	</table><table border=\'1\' width=\'100%\' bordercolor=\'#CAE2F8\' height=\'159\' style=\'border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: rgb(225, 225, 225); border-collapse: collapse; color: rgb(51, 51, 51); font-size: 24px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 36px; orphans: auto; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; font-family: Simsun;\'>");
document.writeln("	<tr style=\'border: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<td bgcolor=\'#ffffff\' height=\'21\' width=\'99%\' style=\'word-break: break-all; font-size: 12px; color: rgb(0, 0, 0); border: 1px solid rgb(225, 225, 225); padding-left: 2px; padding-right: 2px; padding-top: 3px; padding-bottom: 3px\'>");
document.writeln("		<span style=\"color: rgb(51, 51, 51); font-family: 微软雅黑; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 255, 255)\">");
document.writeln("		104期：</span><span style=\"font-family: 微软雅黑; font-size: 14px; color: #333333; background-color: #FFFFFF\">男子创业几十载，屡屡失落总结道：武则天证明了成功和性别没关系，姜子牙证明了成功和年龄没关系，朱元璋证明了成功和出身没关系，马云证明了成功和长相没关系，比尔盖茨证明了成功和学历没关系，而我证明了成功和我没关系。</span></tr>");
document.writeln("	<tr style=\'border: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<td bgcolor=\'#ffffff\' height=\'21\' width=\'99%\' style=\'word-break: break-all; font-size: 12px; color: rgb(0, 0, 0); border: 1px solid rgb(225, 225, 225); padding-left: 2px; padding-right: 2px; padding-top: 3px; padding-bottom: 3px\'>");
document.writeln("		<p align=\'center\' style=\'margin: 0px; padding: 0px\'>");
document.writeln("		<font face=\'微软雅黑\' style=\'font-size: 11pt\'>解：文中讲男子创业，创业即开始，第一起跑线，第一位男肖鼠；本期开鼠肖</font></td>");
document.writeln("	</tr>	");
document.writeln("	");
document.writeln("");
document.writeln("	<!-----------------生活幽默-------------------------------->	<!-----------------生活幽默-------------------------------->");
document.writeln("	<tr style=\'border: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<td bgcolor=\'#FF9900\' height=\'46\' width=\'97%\' style=\'border: 1px solid rgb(225, 225, 225); padding: 3px 2px; word-break: break-all; font-size: 12px; color: rgb(0, 0, 0);\'>");
document.writeln("		<p style=\"text-align: center\">");
document.writeln("		<span style=\"color: rgb(0, 0, 0); font-family: 微软雅黑; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: -webkit-center; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 153, 0)\">");
document.writeln("		<font size=\"3\">800000000.cc</font></span><span style=\"background-color: #FF9900\"><font size=\"3\"><span style=\"font-family: 微软雅黑\">生活幽默解玄机-经典原创</span></font></span></td>");
document.writeln("	</tr>");
document.writeln("	</table><table border=\'1\' width=\'100%\' bordercolor=\'#CAE2F8\' height=\'159\' style=\'border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: rgb(225, 225, 225); border-collapse: collapse; color: rgb(51, 51, 51); font-size: 24px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 36px; orphans: auto; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; font-family: Simsun;\'>");
document.writeln("	<tr style=\'border: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<td bgcolor=\'#ffffff\' height=\'21\' width=\'99%\' style=\'word-break: break-all; font-size: 12px; color: rgb(0, 0, 0); border: 1px solid rgb(225, 225, 225); padding-left: 2px; padding-right: 2px; padding-top: 3px; padding-bottom: 3px\'>");
document.writeln("		<span style=\"color: rgb(51, 51, 51); font-family: 微软雅黑; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 255, 255)\">");
document.writeln("		103期：夫妻要行房碍两个小孩子在，等大的睡了，小的还不睡。就告诉小的看妈妈和爹爹作戏。妻骑上夫身上作倒插莲花，小的不懂事爬到他妈身上，父亲气他妨碍事情，打他下去，小的大哭，大的在一边装睡也骂着：该打叫你看戏，谁叫你爬到戏台上去了。</span></tr>");
document.writeln("	<tr style=\'border: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<td bgcolor=\'#ffffff\' height=\'21\' width=\'99%\' style=\'word-break: break-all; font-size: 12px; color: rgb(0, 0, 0); border: 1px solid rgb(225, 225, 225); padding-left: 2px; padding-right: 2px; padding-top: 3px; padding-bottom: 3px\'>");
document.writeln("		<p align=\'center\' style=\'margin: 0px; padding: 0px\'>");
document.writeln("		<font face=\'微软雅黑\' style=\'font-size: 11pt\'>解：文中讲夫妻要行房小孩还不睡，可看出在夜晚（夜肖）倒插可为后（后肖），鸡狗猪属夜肖与后肖，本期开狗肖。</font></td>");
document.writeln("	</tr>	");
document.writeln("	");
document.writeln("");
document.writeln("	<!-----------------生活幽默-------------------------------->	<!-----------------生活幽默-------------------------------->");
document.writeln("	<tr style=\'border: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<td bgcolor=\'#FF9900\' height=\'46\' width=\'97%\' style=\'border: 1px solid rgb(225, 225, 225); padding: 3px 2px; word-break: break-all; font-size: 12px; color: rgb(0, 0, 0);\'>");
document.writeln("		<p style=\"text-align: center\">");
document.writeln("		<span style=\"color: rgb(0, 0, 0); font-family: 微软雅黑; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: -webkit-center; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 153, 0)\">");
document.writeln("		<font size=\"3\">800000000.cc</font></span><span style=\"background-color: #FF9900\"><font size=\"3\"><span style=\"font-family: 微软雅黑\">生活幽默解玄机-经典原创</span></font></span></td>");
document.writeln("	</tr>");
document.writeln("	</table><table border=\'1\' width=\'100%\' bordercolor=\'#CAE2F8\' height=\'159\' style=\'border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: rgb(225, 225, 225); border-collapse: collapse; color: rgb(51, 51, 51); font-size: 24px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 36px; orphans: auto; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; font-family: Simsun;\'>");
document.writeln("	<tr style=\'border: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<td bgcolor=\'#ffffff\' height=\'21\' width=\'99%\' style=\'word-break: break-all; font-size: 12px; color: rgb(0, 0, 0); border: 1px solid rgb(225, 225, 225); padding-left: 2px; padding-right: 2px; padding-top: 3px; padding-bottom: 3px\'>");
document.writeln("		<span style=\"color: rgb(51, 51, 51); font-family: 微软雅黑; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 255, 255)\">");
document.writeln("		102期：男小伙脱下衣服给女友看他胸前的二头肌说：你看这相当于五十公斤的炸药，又脱下裤子指着他的大腿说：这相当于一百公斤的炸药，接着又脱下内裤，女友夺门狂奔惊叫道：我的天呐！引线这麽短！</span></tr>");
document.writeln("	<tr style=\'border: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<td bgcolor=\'#ffffff\' height=\'21\' width=\'99%\' style=\'word-break: break-all; font-size: 12px; color: rgb(0, 0, 0); border: 1px solid rgb(225, 225, 225); padding-left: 2px; padding-right: 2px; padding-top: 3px; padding-bottom: 3px\'>");
document.writeln("		<p align=\'center\' style=\'margin: 0px; padding: 0px\'>");
document.writeln("		<font face=\'微软雅黑\' style=\'font-size: 11pt\'>解：文中讲男小伙脱衣服给女友看他胸前的二头肌，指前肖中强壮的凶肖虎，本期虎肖。</font></td>");
document.writeln("	</tr>	");
document.writeln("	");
document.writeln("");
document.writeln("	<!-----------------生活幽默-------------------------------->	<!-----------------生活幽默-------------------------------->");
document.writeln("	<tr style=\'border: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<td bgcolor=\'#FF9900\' height=\'46\' width=\'97%\' style=\'border: 1px solid rgb(225, 225, 225); padding: 3px 2px; word-break: break-all; font-size: 12px; color: rgb(0, 0, 0);\'>");
document.writeln("		<p style=\"text-align: center\">");
document.writeln("		<span style=\"color: rgb(0, 0, 0); font-family: 微软雅黑; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: -webkit-center; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 153, 0)\">");
document.writeln("		<font size=\"3\">800000000.cc</font></span><span style=\"background-color: #FF9900\"><font size=\"3\"><span style=\"font-family: 微软雅黑\">生活幽默解玄机-经典原创</span></font></span></td>");
document.writeln("	</tr>");
document.writeln("	</table><table border=\'1\' width=\'100%\' bordercolor=\'#CAE2F8\' height=\'159\' style=\'border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: rgb(225, 225, 225); border-collapse: collapse; color: rgb(51, 51, 51); font-size: 24px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 36px; orphans: auto; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; font-family: Simsun;\'>");
document.writeln("	<tr style=\'border: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<td bgcolor=\'#ffffff\' height=\'21\' width=\'99%\' style=\'word-break: break-all; font-size: 12px; color: rgb(0, 0, 0); border: 1px solid rgb(225, 225, 225); padding-left: 2px; padding-right: 2px; padding-top: 3px; padding-bottom: 3px\'>");
document.writeln("		<span style=\"color: rgb(51, 51, 51); font-family: 微软雅黑; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 255, 255)\">");
document.writeln("		101期：有个人每天给个乞丐十元钱，后来变成五元再后来变成两元，乞丐问他怎给的越来越少了，他就说，之前我是单身给十块，后来我有老婆了只能给五块，再后来我有儿子了，只能给你两块了，乞丐听了大怒说：你怎么能拿我的钱养你的老婆孩子呢？</span></tr>");
document.writeln("	<tr style=\'border: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<td bgcolor=\'#ffffff\' height=\'21\' width=\'99%\' style=\'word-break: break-all; font-size: 12px; color: rgb(0, 0, 0); border: 1px solid rgb(225, 225, 225); padding-left: 2px; padding-right: 2px; padding-top: 3px; padding-bottom: 3px\'>");
document.writeln("		<p align=\'center\' style=\'margin: 0px; padding: 0px\'>");
document.writeln("		<font face=\'微软雅黑\' style=\'font-size: 11pt\'>解：文中讲你怎么能拿我的钱养你的老婆孩子呢，子鼠，本期开鼠肖");
document.writeln("		。</font></td>");
document.writeln("	</tr>	");
document.writeln("	");
document.writeln("");
document.writeln("	<!-----------------生活幽默-------------------------------->	<!-----------------生活幽默-------------------------------->");
document.writeln("	<tr style=\'border: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<td bgcolor=\'#FF9900\' height=\'46\' width=\'97%\' style=\'border: 1px solid rgb(225, 225, 225); padding: 3px 2px; word-break: break-all; font-size: 12px; color: rgb(0, 0, 0);\'>");
document.writeln("		<p style=\"text-align: center\">");
document.writeln("		<span style=\"color: rgb(0, 0, 0); font-family: 微软雅黑; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: -webkit-center; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 153, 0)\">");
document.writeln("		<font size=\"3\">800000000.cc</font></span><span style=\"background-color: #FF9900\"><font size=\"3\"><span style=\"font-family: 微软雅黑\">生活幽默解玄机-经典原创</span></font></span></td>");
document.writeln("	</tr>");
document.writeln("	</table><table border=\'1\' width=\'100%\' bordercolor=\'#CAE2F8\' height=\'159\' style=\'border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: rgb(225, 225, 225); border-collapse: collapse; color: rgb(51, 51, 51); font-size: 24px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 36px; orphans: auto; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; font-family: Simsun;\'>");
document.writeln("	<tr style=\'border: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<td bgcolor=\'#ffffff\' height=\'21\' width=\'99%\' style=\'word-break: break-all; font-size: 12px; color: rgb(0, 0, 0); border: 1px solid rgb(225, 225, 225); padding-left: 2px; padding-right: 2px; padding-top: 3px; padding-bottom: 3px\'>");
document.writeln("		<span style=\"color: rgb(51, 51, 51); font-family: 微软雅黑; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 255, 255)\">");
document.writeln("		100期：十字路口停红灯，有个妈妈背个小孩，前面还载个大一点的，被交警拦住，交警说：这位小姐，你小孩没带安全帽也就算了，你怎也不戴？妈妈说：小朋友这麽小买不到！交警说：你自已呢！妈妈说：我带干嘛，万一我的孩子出了什麽事，我也不想活了！</span></tr>");
document.writeln("	<tr style=\'border: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<td bgcolor=\'#ffffff\' height=\'21\' width=\'99%\' style=\'word-break: break-all; font-size: 12px; color: rgb(0, 0, 0); border: 1px solid rgb(225, 225, 225); padding-left: 2px; padding-right: 2px; padding-top: 3px; padding-bottom: 3px\'>");
document.writeln("		<p align=\'center\' style=\'margin: 0px; padding: 0px\'>");
document.writeln("		<font face=\'微软雅黑\' style=\'font-size: 11pt\'>解：红灯解得出红波，小朋友这麽小买不到，综合解得，红波小数。</font></td>");
document.writeln("	</tr>	");
document.writeln("	");
document.writeln("");
document.writeln("	<!-----------------生活幽默-------------------------------->	<!-----------------生活幽默-------------------------------->");
document.writeln("	<tr style=\'border: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<td bgcolor=\'#FF9900\' height=\'46\' width=\'97%\' style=\'border: 1px solid rgb(225, 225, 225); padding: 3px 2px; word-break: break-all; font-size: 12px; color: rgb(0, 0, 0);\'>");
document.writeln("		<p style=\"text-align: center\">");
document.writeln("		<span style=\"color: rgb(0, 0, 0); font-family: 微软雅黑; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: -webkit-center; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 153, 0)\">");
document.writeln("		<font size=\"3\">800000000.cc</font></span><span style=\"background-color: #FF9900\"><font size=\"3\"><span style=\"font-family: 微软雅黑\">生活幽默解玄机-经典原创</span></font></span></td>");
document.writeln("	</tr>");
document.writeln("	</table><table border=\'1\' width=\'100%\' bordercolor=\'#CAE2F8\' height=\'159\' style=\'border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: rgb(225, 225, 225); border-collapse: collapse; color: rgb(51, 51, 51); font-size: 24px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 36px; orphans: auto; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; font-family: Simsun;\'>");
document.writeln("	<tr style=\'border: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<td bgcolor=\'#ffffff\' height=\'21\' width=\'99%\' style=\'word-break: break-all; font-size: 12px; color: rgb(0, 0, 0); border: 1px solid rgb(225, 225, 225); padding-left: 2px; padding-right: 2px; padding-top: 3px; padding-bottom: 3px\'>");
document.writeln("		<span style=\"font-family: 微软雅黑; font-size: 14px; color: #333333; background-color: #FFFFFF\">");
document.writeln("		099</span><span style=\"color: rgb(51, 51, 51); font-family: 微软雅黑; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 255, 255)\">期：</span><span style=\"font-family: 微软雅黑; font-size: 14px; color: #333333; background-color: #FFFFFF\">一读书人见邻居要砍掉庭院中的一棵大树，上前问道：这株桂花树长得甚好，老伯何故砍掉？邻居叹曰：我这庭院四四方方，有了此树，便成了个困字，怕不吉利，读书人拱手笑道：依老伯说法，除去树后住人，不成了个囚犯的囚字吗，岂非更不吉利?</span></tr>");
document.writeln("	<tr style=\'border: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<td bgcolor=\'#ffffff\' height=\'21\' width=\'99%\' style=\'word-break: break-all; font-size: 12px; color: rgb(0, 0, 0); border: 1px solid rgb(225, 225, 225); padding-left: 2px; padding-right: 2px; padding-top: 3px; padding-bottom: 3px\'>");
document.writeln("		<p align=\'center\' style=\'margin: 0px; padding: 0px\'>");
document.writeln("		<font face=\'微软雅黑\' style=\'font-size: 11pt\'>解：文中若要嫁给你，羞死我一家，指家肖牛马羊鸡狗猪，本期开狗肖");
document.writeln("		。</font></td>");
document.writeln("	</tr>	");
document.writeln("	");
document.writeln("");
document.writeln("	<!-----------------生活幽默-------------------------------->	<!-----------------生活幽默-------------------------------->");
document.writeln("	<tr style=\'border: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<td bgcolor=\'#FF9900\' height=\'46\' width=\'97%\' style=\'border: 1px solid rgb(225, 225, 225); padding: 3px 2px; word-break: break-all; font-size: 12px; color: rgb(0, 0, 0);\'>");
document.writeln("		<p style=\"text-align: center\">");
document.writeln("		<span style=\"color: rgb(0, 0, 0); font-family: 微软雅黑; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: -webkit-center; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 153, 0)\">");
document.writeln("		<font size=\"3\">800000000.cc</font></span><span style=\"background-color: #FF9900\"><font size=\"3\"><span style=\"font-family: 微软雅黑\">生活幽默解玄机-经典原创</span></font></span></td>");
document.writeln("	</tr>");
document.writeln("	</table><table border=\'1\' width=\'100%\' bordercolor=\'#CAE2F8\' height=\'159\' style=\'border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: rgb(225, 225, 225); border-collapse: collapse; color: rgb(51, 51, 51); font-size: 24px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 36px; orphans: auto; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; font-family: Simsun;\'>");
document.writeln("	<tr style=\'border: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<td bgcolor=\'#ffffff\' height=\'21\' width=\'99%\' style=\'word-break: break-all; font-size: 12px; color: rgb(0, 0, 0); border: 1px solid rgb(225, 225, 225); padding-left: 2px; padding-right: 2px; padding-top: 3px; padding-bottom: 3px\'>");
document.writeln("		<span style=\"font-family: 微软雅黑; font-size: 14px; color: #333333; background-color: #FFFFFF\">");
document.writeln("		098</span><span style=\"color: rgb(51, 51, 51); font-family: 微软雅黑; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 255, 255)\">期：一读书人见邻居要砍掉庭院中的一棵大树，上前问道：这株桂花树长得甚好，老伯何故砍掉？邻居叹曰：我这庭院四四方方，有了此树，便成了个困字，怕不吉利，读书人拱手笑道：依老伯说法，除去树后住人，不成了个囚犯的囚字吗，岂非更不吉利?</span></tr>");
document.writeln("	<tr style=\'border: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<td bgcolor=\'#ffffff\' height=\'21\' width=\'99%\' style=\'word-break: break-all; font-size: 12px; color: rgb(0, 0, 0); border: 1px solid rgb(225, 225, 225); padding-left: 2px; padding-right: 2px; padding-top: 3px; padding-bottom: 3px\'>");
document.writeln("		<p align=\'center\' style=\'margin: 0px; padding: 0px\'>");
document.writeln("		<font face=\'微软雅黑\' style=\'font-size: 11pt\'>解：文中讲庭院四四方方成困与囚字，生肖中唯狗带有四四方方的口字，本期开狗肖。</font></td>");
document.writeln("	</tr>	");
document.writeln("	");
document.writeln("");
document.writeln("	<!-----------------生活幽默-------------------------------->");
document.writeln("<!-----------------生活幽默-------------------------------->");
document.writeln("	<tr style=\'border: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<td bgcolor=\'#FF9900\' height=\'46\' width=\'97%\' style=\'border: 1px solid rgb(225, 225, 225); padding: 3px 2px; word-break: break-all; font-size: 12px; color: rgb(0, 0, 0);\'>");
document.writeln("		<p style=\"text-align: center\">");
document.writeln("		<span style=\"color: rgb(0, 0, 0); font-family: 微软雅黑; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: -webkit-center; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 153, 0)\">");
document.writeln("		<font size=\"3\">800000000.cc</font></span><span style=\"background-color: #FF9900\"><font size=\"3\"><span style=\"font-family: 微软雅黑\">生活幽默解玄机-经典原创</span></font></span></td>");
document.writeln("	</tr>");
document.writeln("	</table><table border=\'1\' width=\'100%\' bordercolor=\'#CAE2F8\' height=\'159\' style=\'border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: rgb(225, 225, 225); border-collapse: collapse; color: rgb(51, 51, 51); font-size: 24px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 36px; orphans: auto; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; font-family: Simsun;\'>");
document.writeln("	<tr style=\'border: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<td bgcolor=\'#ffffff\' height=\'21\' width=\'99%\' style=\'word-break: break-all; font-size: 12px; color: rgb(0, 0, 0); border: 1px solid rgb(225, 225, 225); padding-left: 2px; padding-right: 2px; padding-top: 3px; padding-bottom: 3px\'>");
document.writeln("		<span style=\"font-family: 微软雅黑; font-size: 14px; color: #333333; background-color: #FFFFFF\">");
document.writeln("		097</span><span style=\"color: rgb(51, 51, 51); font-family: 微软雅黑; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 255, 255)\">期：</span><span style=\"font-family: 微软雅黑; font-size: 14px; color: #333333; background-color: #FFFFFF\">小伙刚到女友家，便迫不及待的要亲吻女友！女友说：不行，我大姨妈来了！小伙感到很奇怪：亲嘴和大姨妈有什么关系？于是男生强吻女友，突然一妇女从厨房冲出来 妇女指着男生骂道：为什么欺负我的外甥女！</span></tr>");
document.writeln("	<tr style=\'border: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<td bgcolor=\'#ffffff\' height=\'21\' width=\'99%\' style=\'word-break: break-all; font-size: 12px; color: rgb(0, 0, 0); border: 1px solid rgb(225, 225, 225); padding-left: 2px; padding-right: 2px; padding-top: 3px; padding-bottom: 3px\'>");
document.writeln("		<p align=\'center\' style=\'margin: 0px; padding: 0px\'>");
document.writeln("		<font face=\'微软雅黑\' style=\'font-size: 11pt\'>解：文中讲小伙到女友家，指家肖中的女肖羊鸡猪，本期开鸡肖。</font></td>");
document.writeln("	</tr>	");
document.writeln("	");
document.writeln("");
document.writeln("	<!-----------------生活幽默-------------------------------->");
document.writeln("	<tr style=\'border: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<td bgcolor=\'#FF9900\' height=\'46\' width=\'97%\' style=\'border: 1px solid rgb(225, 225, 225); padding: 3px 2px; word-break: break-all; font-size: 12px; color: rgb(0, 0, 0);\'>");
document.writeln("		<p style=\"text-align: center\">");
document.writeln("		<span style=\"color: rgb(0, 0, 0); font-family: 微软雅黑; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: -webkit-center; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 153, 0)\">");
document.writeln("		<font size=\"3\">800000000.cc</font></span><span style=\"background-color: #FF9900\"><font size=\"3\"><span style=\"font-family: 微软雅黑\">生活幽默解玄机-经典原创</span></font></span></td>");
document.writeln("	</tr>");
document.writeln("	</table><table border=\'1\' width=\'100%\' bordercolor=\'#CAE2F8\' height=\'159\' style=\'border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: rgb(225, 225, 225); border-collapse: collapse; color: rgb(51, 51, 51); font-size: 24px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 36px; orphans: auto; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; font-family: Simsun;\'>");
document.writeln("	<tr style=\'border: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<td bgcolor=\'#ffffff\' height=\'21\' width=\'99%\' style=\'word-break: break-all; font-size: 12px; color: rgb(0, 0, 0); border: 1px solid rgb(225, 225, 225); padding-left: 2px; padding-right: 2px; padding-top: 3px; padding-bottom: 3px\'>");
document.writeln("		<span style=\"font-family: 微软雅黑; font-size: 14px; color: #333333; background-color: #FFFFFF\">");
document.writeln("		096</span><span style=\"color: rgb(51, 51, 51); font-family: 微软雅黑; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 255, 255)\">期：保镖公司前来应聘的人排成了长龙，主考便叫有特殊才能的出来表演他们的拿手绝活。出来的人分别表演了拳击、空手道、剑术以及射击等。轮到最后一位，却站着不动。主考问：您等什么？那人说：对不起各位，我是操纵原子弹的。</span></tr>");
document.writeln("	<tr style=\'border: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<td bgcolor=\'#ffffff\' height=\'21\' width=\'99%\' style=\'word-break: break-all; font-size: 12px; color: rgb(0, 0, 0); border: 1px solid rgb(225, 225, 225); padding-left: 2px; padding-right: 2px; padding-top: 3px; padding-bottom: 3px\'>");
document.writeln("		<p align=\'center\' style=\'margin: 0px; padding: 0px\'>");
document.writeln("		<font face=\'微软雅黑\' style=\'font-size: 11pt\'>解：文中讲出来的人分别表演他们的拿手绝活，可谓各耍各大的绝活，即耍猴，开猴肖。</font></td>");
document.writeln("	</tr>	");
document.writeln("	");
document.writeln("");
document.writeln("	<!-----------------生活幽默-------------------------------->	<!-----------------生活幽默-------------------------------->");
document.writeln("	<tr style=\'border: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<td bgcolor=\'#FF9900\' height=\'46\' width=\'97%\' style=\'border: 1px solid rgb(225, 225, 225); padding: 3px 2px; word-break: break-all; font-size: 12px; color: rgb(0, 0, 0);\'>");
document.writeln("		<p style=\"text-align: center\">");
document.writeln("		<span style=\"color: rgb(0, 0, 0); font-family: 微软雅黑; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: -webkit-center; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 153, 0)\">");
document.writeln("		<font size=\"3\">800000000.cc</font></span><span style=\"background-color: #FF9900\"><font size=\"3\"><span style=\"font-family: 微软雅黑\">生活幽默解玄机-经典原创</span></font></span></td>");
document.writeln("	</tr>");
document.writeln("	</table><table border=\'1\' width=\'100%\' bordercolor=\'#CAE2F8\' height=\'159\' style=\'border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: rgb(225, 225, 225); border-collapse: collapse; color: rgb(51, 51, 51); font-size: 24px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 36px; orphans: auto; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; font-family: Simsun;\'>");
document.writeln("	<tr style=\'border: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<td bgcolor=\'#ffffff\' height=\'21\' width=\'99%\' style=\'word-break: break-all; font-size: 12px; color: rgb(0, 0, 0); border: 1px solid rgb(225, 225, 225); padding-left: 2px; padding-right: 2px; padding-top: 3px; padding-bottom: 3px\'>");
document.writeln("		<span style=\"font-family: 微软雅黑; font-size: 14px; color: #333333; background-color: #FFFFFF\">");
document.writeln("		095</span><span style=\"color: rgb(51, 51, 51); font-family: 微软雅黑; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 255, 255)\">期：领导到边防部队体验生活，问士兵性生活怎么解决，士兵指着母骆驼：都靠它！领导摇头。又一月领导实在受不了，叫兵把骆驼弄帐篷来。然后费半天劲把骆驼办了。事毕，领导感慨：你们每次都这么费事么? 兵摇头：我们平时都是骑它去镇上找姑娘！</span></tr>");
document.writeln("	<tr style=\'border: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<td bgcolor=\'#ffffff\' height=\'21\' width=\'99%\' style=\'word-break: break-all; font-size: 12px; color: rgb(0, 0, 0); border: 1px solid rgb(225, 225, 225); padding-left: 2px; padding-right: 2px; padding-top: 3px; padding-bottom: 3px\'>");
document.writeln("		<p align=\'center\' style=\'margin: 0px; padding: 0px\'>");
document.writeln("		<font face=\'微软雅黑\' style=\'font-size: 11pt\'>解：骆驼体形大，相似体形大的生肖：牛马，综合开牛。</font></td>");
document.writeln("	</tr>	");
document.writeln("	");
document.writeln("");
document.writeln("	<!-----------------生活幽默-------------------------------->");
document.writeln("<!-----------------生活幽默-------------------------------->");
document.writeln("	<tr style=\'border: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<td bgcolor=\'#FF9900\' height=\'46\' width=\'97%\' style=\'border: 1px solid rgb(225, 225, 225); padding: 3px 2px; word-break: break-all; font-size: 12px; color: rgb(0, 0, 0);\'>");
document.writeln("		<p style=\"text-align: center\">");
document.writeln("		<span style=\"color: rgb(0, 0, 0); font-family: 微软雅黑; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: -webkit-center; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 153, 0)\">");
document.writeln("		<font size=\"3\">800000000.cc</font></span><span style=\"background-color: #FF9900\"><font size=\"3\"><span style=\"font-family: 微软雅黑\">生活幽默解玄机-经典原创</span></font></span></td>");
document.writeln("	</tr>");
document.writeln("	</table><table border=\'1\' width=\'100%\' bordercolor=\'#CAE2F8\' height=\'159\' style=\'border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: rgb(225, 225, 225); border-collapse: collapse; color: rgb(51, 51, 51); font-size: 24px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 36px; orphans: auto; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; font-family: Simsun;\'>");
document.writeln("	<tr style=\'border: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<td bgcolor=\'#ffffff\' height=\'21\' width=\'99%\' style=\'word-break: break-all; font-size: 12px; color: rgb(0, 0, 0); border: 1px solid rgb(225, 225, 225); padding-left: 2px; padding-right: 2px; padding-top: 3px; padding-bottom: 3px\'>");
document.writeln("		<span style=\"font-family: 微软雅黑; font-size: 14px; color: #333333; background-color: #FFFFFF\">");
document.writeln("		094</span><span style=\"color: rgb(51, 51, 51); font-family: 微软雅黑; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 255, 255)\">期：突然发现了个事,武则天证明了成功和性别没关系,姜子牙证明了成功和年龄没关系,朱元璋证明了成功和出身没关系,马云证明了成功和长相没关系,比尔盖茨证明了成功和学历没关系,而我就比较厉害,我证明了成功和我没关系!</span></tr>");
document.writeln("	<tr style=\'border: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<td bgcolor=\'#ffffff\' height=\'21\' width=\'99%\' style=\'word-break: break-all; font-size: 12px; color: rgb(0, 0, 0); border: 1px solid rgb(225, 225, 225); padding-left: 2px; padding-right: 2px; padding-top: 3px; padding-bottom: 3px\'>");
document.writeln("		<p align=\'center\' style=\'margin: 0px; padding: 0px\'>");
document.writeln("		<font face=\'微软雅黑\' style=\'font-size: 11pt\'>解：武则天指女肖，水性杨花，综合开羊。</font></td>");
document.writeln("	</tr>	");
document.writeln("	");
document.writeln("");
document.writeln("	<!-----------------生活幽默-------------------------------->");
document.writeln("");
document.writeln("<!-----------------生活幽默-------------------------------->");
document.writeln("	<tr style=\'border: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<td bgcolor=\'#FF9900\' height=\'46\' width=\'97%\' style=\'border: 1px solid rgb(225, 225, 225); padding: 3px 2px; word-break: break-all; font-size: 12px; color: rgb(0, 0, 0);\'>");
document.writeln("		<p style=\"text-align: center\">");
document.writeln("		<span style=\"color: rgb(0, 0, 0); font-family: 微软雅黑; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: -webkit-center; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 153, 0)\">");
document.writeln("		<font size=\"3\">800000000.cc</font></span><span style=\"background-color: #FF9900\"><font size=\"3\"><span style=\"font-family: 微软雅黑\">生活幽默解玄机-经典原创</span></font></span></td>");
document.writeln("	</tr>");
document.writeln("	</table><table border=\'1\' width=\'100%\' bordercolor=\'#CAE2F8\' height=\'159\' style=\'border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: rgb(225, 225, 225); border-collapse: collapse; color: rgb(51, 51, 51); font-size: 24px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 36px; orphans: auto; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; font-family: Simsun;\'>");
document.writeln("	<tr style=\'border: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<td bgcolor=\'#ffffff\' height=\'21\' width=\'99%\' style=\'word-break: break-all; font-size: 12px; color: rgb(0, 0, 0); border: 1px solid rgb(225, 225, 225); padding-left: 2px; padding-right: 2px; padding-top: 3px; padding-bottom: 3px\'>");
document.writeln("		<span style=\"font-family: 微软雅黑; font-size: 14px; color: #333333; background-color: #FFFFFF\">");
document.writeln("		093</span><span style=\"color: rgb(51, 51, 51); font-family: 微软雅黑; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 255, 255)\">期：昨天逛街钱包被偷了,今天有人敲门,开门看是一男的,他说在草丛发现个钱包,然后顺着暂住证上的地址就找到我住的地方了。出于礼仪我请他进家里喝杯茶,他坐了一会儿就走了。下午我出去玩,回来一看,桌子上的笔记本电脑不见了。。。</span></tr>");
document.writeln("	<tr style=\'border: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<td bgcolor=\'#ffffff\' height=\'21\' width=\'99%\' style=\'word-break: break-all; font-size: 12px; color: rgb(0, 0, 0); border: 1px solid rgb(225, 225, 225); padding-left: 2px; padding-right: 2px; padding-top: 3px; padding-bottom: 3px\'>");
document.writeln("		<p align=\'center\' style=\'margin: 0px; padding: 0px\'>");
document.writeln("		<font face=\'微软雅黑\' style=\'font-size: 11pt\'>解：火中取栗，综合开兔。</font></td>");
document.writeln("	</tr>	");
document.writeln("	");
document.writeln("");
document.writeln("	<!-----------------生活幽默-------------------------------->");
document.writeln("");
document.writeln("	<!-----------------生活幽默-------------------------------->");
document.writeln("	</table>");
document.writeln("");
document.writeln("</html>");